/**
 * List of all dashboard routes: path (without leading slash) and page key.
 * Add new pages here and in the PAGES object in routes.tsx.
 */
import { ROUTES } from "./config"

export const toChildPath = (r: string | undefined) => (r ?? "").replace(/^\//, "")

export const DASHBOARD_ROUTES: { index?: true; path?: string; page: string }[] = [
  { index: true, page: "Dashboard" },
  // Visitor Management Overview (first under Visitor Management dropdown)
  { path: toChildPath(ROUTES.VISITOR_MANAGEMENT_OVERVIEW), page: "VisitorManagementOverview" },
  // Registration
  { path: toChildPath(ROUTES.PRE_REGISTRATION), page: "PreRegistration" },
  { path: toChildPath(ROUTES.WALK_IN_REGISTRATION), page: "WalkInRegistration" },
  { path: toChildPath(ROUTES.VISITOR_DETAIL), page: "VisitorDetail" },
  { path: toChildPath(ROUTES.STREAMED_UPLOAD), page: "StreamedUpload" },
  { path: toChildPath(ROUTES.PHOTO_CAPTURE), page: "PhotoCapture" },
  { path: toChildPath(ROUTES.QR_CODE_GENERATION), page: "QRCodeGeneration" },
  { path: toChildPath(ROUTES.APPOINTMENT_SCHEDULING), page: "AppointmentScheduling" },
  { path: toChildPath(ROUTES.TIME_SLOT_BOOKING), page: "TimeSlotBooking" },
  { path: toChildPath(ROUTES.HOST_SELECTION), page: "HostSelection" },
  { path: toChildPath(ROUTES.VISIT_PURPOSE), page: "VisitPurpose" },
  { path: toChildPath(ROUTES.CALENDAR_VIEW), page: "CalendarView" },
  { path: toChildPath(ROUTES.SECURITY_SCREENING), page: "SecurityScreening" },
  { path: toChildPath(ROUTES.WATCHLIST_SCREENING), page: "WatchlistScreening" },
  { path: toChildPath(ROUTES.BLACKLIST_MANAGEMENT), page: "BlacklistManagement" },
  { path: toChildPath(ROUTES.FLAGGED_VISITOR_ALERTS), page: "FlaggedVisitorAlerts" },
  { path: toChildPath(ROUTES.ACCESS_CONTROL), page: "AccessControl" },
  { path: toChildPath(ROUTES.ZONE_RESTRICTIONS), page: "ZoneRestrictions" },
  { path: toChildPath(ROUTES.GATE_INTEGRATION), page: "GateIntegration" },
  { path: toChildPath(ROUTES.ESCORT_REQUIREMENT), page: "EscortRequirement" },
  { path: toChildPath(ROUTES.HOST_DEPARTMENT_DASHBOARD), page: "HostDepartmentDashboard" },
  { path: toChildPath(ROUTES.VISITOR_NOTIFICATIONS), page: "VisitorNotifications" },
  { path: toChildPath(ROUTES.UPCOMING_VISITS), page: "UpcomingVisits" },
  { path: toChildPath(ROUTES.VISITOR_HISTORY), page: "VisitorHistory" },
  { path: toChildPath(ROUTES.GUARD_RECEPTION_PANEL), page: "GuardReceptionPanel" },
  { path: toChildPath(ROUTES.VEHICLE_CONTRACTOR_MANAGEMENT), page: "VehicleContractorManagement" },
  { path: toChildPath(ROUTES.VEHICLE_REGISTRATION), page: "VehicleRegistration" },
  { path: toChildPath(ROUTES.VEHICLE_TRACKING), page: "VehicleTracking" },
  { path: toChildPath(ROUTES.CONTRACTOR_PASSES), page: "ContractorPasses" },
  { path: toChildPath(ROUTES.CARGO_DELIVERY_LOGS), page: "CargoDeliveryLogs" },
  // Armory
  { path: toChildPath(ROUTES.ARMORY), page: "Armory" },
  // Warehouse
  { path: toChildPath(ROUTES.WAREHOUSE_SETUP), page: "WarehouseSetup" },
  { path: toChildPath(ROUTES.ZONE_LOCATION_MANAGEMENT), page: "ZoneLocationManagement" },
  { path: toChildPath(ROUTES.STORAGE_ALLOCATION), page: "StorageAllocation" },
  { path: toChildPath(ROUTES.INVENTORY_TRACKING), page: "InventoryTracking" },
  { path: toChildPath(ROUTES.STOCK_RECONCILIATION), page: "StockReconciliation" },
  { path: toChildPath(ROUTES.RELEASE_INVENTORY), page: "ReleaseInventory" },
  { path: toChildPath(ROUTES.MEMO_DISTRIBUTION), page: "MemoDistribution" },
  { path: toChildPath(ROUTES.DESTRUCTION), page: "MemoDistribution" },
  { path: "destruction/:id", page: "DestructionRecordDetail" },
  { path: toChildPath(ROUTES.HS_CODES_FILE), page: "HSCodesFile" },
  { path: toChildPath(ROUTES.DEPOSIT_ACCOUNT_REGISTER), page: "DepositAccountRegister" },
  { path: "deposit-account-register/:id", page: "DepositAccountRegisterDetail" },
  { path: toChildPath(ROUTES.DETENTION_MEMO), page: "DetentionMemo" },
  { path: "seizure-management/detention-memo/create", page: "DetentionMemoCreate" },
  { path: "seizure-management/detention-memo/:id", page: "DetentionMemoDetail" },
  // Legacy detention-memo paths (QR codes / old bookmarks)
  { path: "detention-memo", page: "DetentionMemo" },
  { path: "detention-memo/create", page: "DetentionMemoCreate" },
  { path: "detention-memo/:id", page: "DetentionMemoDetail" },
  { path: toChildPath(ROUTES.SEIZED_INVENTORY), page: "SeizedInventory" },
  { path: "seized-inventory/:id", page: "SeizedInventoryDetail" },
  { path: toChildPath(ROUTES.GOODS_RECEIPT), page: "GoodsReceipt" },
  { path: "goods-receipt/:id", page: "GoodsReceiptDetail" },
  { path: toChildPath(ROUTES.STOCK_MANAGEMENT), page: "StockManagement" },
  { path: "stock-management/:id", page: "StockManagementDetail" },
  { path: toChildPath(ROUTES.CYCLE_COUNTING), page: "CycleCountingAudit" },
  { path: "cycle-counting-audit/:id", page: "CycleCountingAuditDetail" },
  { path: toChildPath(ROUTES.INVENTORY_VALUATION), page: "InventoryValuation" },
  { path: "inventory-valuation/:id", page: "InventoryValuationDetail" },
  // Cameras & operations
  { path: toChildPath(ROUTES.CAMERA_INTEGRATION), page: "CameraIntegration" },
  { path: toChildPath(ROUTES.OPERATIONS_DASHBOARD), page: "OperationsDashboard" },
  { path: toChildPath(ROUTES.ANALYTICS_DASHBOARD), page: "AnalyticsDashboard" },
  { path: toChildPath(ROUTES.LIVE_CAMERA_GRID), page: "LiveCameraGrid" },
  { path: toChildPath(ROUTES.VEHICLE_DETECTION), page: "VehicleDetection" },
  { path: toChildPath(ROUTES.AI_MODELS), page: "AiModels" },
  { path: toChildPath(ROUTES.AI_ZONES), page: "AiZones" },
  { path: toChildPath(ROUTES.AI_RULES), page: "AiRules" },
  { path: toChildPath(ROUTES.AI_TRAINING), page: "AiTraining" },
  { path: toChildPath(ROUTES.LIVE_MONITORING), page: "LiveMonitoring" },
  // Seizures
  { path: toChildPath(ROUTES.NEW_SEIZURE_ENTRY), page: "NewSeizureEntry" },
  { path: toChildPath(ROUTES.JCP_TOLL_PLAZA_ENTRY), page: "JcpTollPlazaEntry" },
  { path: toChildPath(ROUTES.GOODS_RECEIPT_HANDOVER), page: "GoodsReceiptHandover" },
  { path: toChildPath(ROUTES.AI_ITEM_CATALOGING), page: "AiItemCataloging" },
  { path: toChildPath(ROUTES.SEIZURE_REGISTER), page: "SeizureRegister" },
  { path: toChildPath(ROUTES.FIR_REGISTRATION), page: "FirRegistration" },
  { path: toChildPath(ROUTES.CASE_FILE_CREATION), page: "CaseFileCreation" },
  { path: toChildPath(ROUTES.COURT_PROCEEDINGS), page: "CourtProceedings" },
  { path: toChildPath(ROUTES.LEGAL_DOCUMENTS), page: "LegalDocuments" },
  { path: toChildPath(ROUTES.CASE_STATUS_TRACKING), page: "CaseStatusTracking" },
  // Seizure Management
  { path: toChildPath(ROUTES.SEIZURE_MANAGEMENT), page: "SeizureManagementDashboard" },
  { path: toChildPath(ROUTES.SEIZURE_MGMT_NOTE_SHEET), page: "SeizureMgmtNoteSheet" },
  { path: "seizure-management/note-sheet/create", page: "SeizureMgmtNoteSheetCreate" },
  { path: "seizure-management/note-sheet/:id/edit", page: "SeizureMgmtNoteSheetEdit" },
  { path: "seizure-management/note-sheet/:id", page: "SeizureMgmtNoteSheetDetail" },
  { path: toChildPath(ROUTES.SEIZURE_MGMT_ASSESSMENT), page: "SeizureMgmtAssessment" },
  { path: "seizure-management/assessment/create", page: "SeizureMgmtAssessmentCreate" },
  { path: "seizure-management/assessment/:id/edit", page: "SeizureMgmtAssessmentEdit" },
  { path: "seizure-management/assessment/:id", page: "SeizureMgmtAssessmentDetail" },
  { path: toChildPath(ROUTES.SEIZURE_MGMT_DETENTION_REPORTING), page: "SeizureMgmtDetentionReporting" },
  { path: toChildPath(ROUTES.SEIZURE_MGMT_RECOVERY_MEMO), page: "SeizureMgmtRecoveryMemo" },
  { path: "seizure-management/recovery-memo/create", page: "SeizureMgmtRecoveryMemoCreate" },
  { path: "seizure-management/recovery-memo/:id", page: "SeizureMgmtRecoveryMemoDetail" },
  { path: toChildPath(ROUTES.SEIZURE_MGMT_RECOVERY_REPORTING), page: "SeizureMgmtRecoveryReporting" },
  { path: toChildPath(ROUTES.SEIZURE_MGMT_SEIZURE_REPORT), page: "SeizureMgmtSeizureReport" },
  { path: "seizure-management/seizure-report/create", page: "SeizureMgmtSeizureReportCreate" },
  { path: "seizure-management/seizure-report/:id", page: "SeizureMgmtSeizureReportDetail" },
  { path: toChildPath(ROUTES.SEIZURE_MGMT_REPORTS), page: "SeizureMgmtReports" },
  // Transfers
  { path: toChildPath(ROUTES.INTER_COLLECTORATE_TRANSFER), page: "InterCollectorateTransfer" },
  { path: toChildPath(ROUTES.INTERNAL_MOVEMENT), page: "InternalMovement" },
  { path: toChildPath(ROUTES.HANDOVER_REQUESTS), page: "HandoverRequests" },
  { path: toChildPath(ROUTES.DOUBLE_AUTHENTICATION), page: "DoubleAuthentication" },
  { path: toChildPath(ROUTES.TRANSFER_TRACKING), page: "TransferTracking" },
  // Inventory
  { path: toChildPath(ROUTES.PERISHABLE_REGISTER), page: "PerishableRegister" },
  { path: toChildPath(ROUTES.EXPIRY_TRACKING), page: "ExpiryTracking" },
  { path: toChildPath(ROUTES.PRIORITY_DISPOSAL_QUEUE), page: "PriorityDisposalQueue" },
  { path: toChildPath(ROUTES.DESTRUCTION_ORDERS), page: "DestructionOrders" },
  { path: toChildPath(ROUTES.LOT_CREATION), page: "LotCreation" },
  { path: toChildPath(ROUTES.ITEM_VALUATION), page: "ItemValuation" },
  // Auction
  { path: toChildPath(ROUTES.ASO_PORTAL_SYNC), page: "AsoPortalSync" },
  { path: toChildPath(ROUTES.BIDDING_MANAGEMENT), page: "BiddingManagement" },
  { path: toChildPath(ROUTES.SALE_COMPLETION), page: "SaleCompletion" },
  { path: toChildPath(ROUTES.REVENUE_REPORTS), page: "RevenueReports" },
  { path: "camera-integration/:id", page: "CameraIntegrationView" },
  { path: "camera-management/:id", page: "CameraManagementView" },
  { path: toChildPath(ROUTES.CAMERA_MANAGEMENT), page: "CameraManagement" },
  { path: "analytics/camera-management/:id", page: "AnalyticsCameraManagementView" },
  { path: toChildPath(ROUTES.ANALYTICS_CAMERA_MANAGEMENT), page: "AnalyticsCameraManagement" },
  { path: toChildPath(ROUTES.OBJECT_DETECTION), page: "ObjectDetection" },
  { path: toChildPath(ROUTES.PERSON_JOURNEY), page: "PersonJourney" },
  { path: "person-journey/:uuid", page: "PersonJourneyDetail" },
  { path: toChildPath(ROUTES.ANPR_SETTINGS), page: "AnprSettings" },
  { path: toChildPath(ROUTES.ANPR_VEHICLE_TRACKING), page: "AnprVehicleTracking" },
  { path: toChildPath(ROUTES.ANOMALY_DETECTION), page: "AnomalyDetection" },
  // Reports
  { path: toChildPath(ROUTES.REPORTS), page: "Reports" },
  { path: toChildPath(ROUTES.STANDARD_REPORTS), page: "Reports" },
  { path: toChildPath(ROUTES.CUSTOM_REPORT_BUILDER), page: "Reports" },
  { path: toChildPath(ROUTES.EXPORT_CENTER), page: "Reports" },
  { path: toChildPath(ROUTES.PREDICTIVE_INSIGHTS), page: "PredictiveInsights" },
  { path: toChildPath(ROUTES.DATA_VISUALIZATION), page: "DataVisualization" },
  // WMS Integration (reuse Integrations page)
  { path: toChildPath(ROUTES.WEBOC_SYNC), page: "Integrations" },
  { path: toChildPath(ROUTES.API_LOGS), page: "Integrations" },
  // WMS User Management (reuse existing pages)
  { path: toChildPath(ROUTES.USER_ACCOUNTS), page: "UserRoleManagement" },
  { path: toChildPath(ROUTES.ROLES_PERMISSIONS), page: "UserRoleManagement" },
  { path: toChildPath(ROUTES.ACTIVITY_LOGS), page: "SecurityAccess" },
  // HR
  { path: toChildPath(ROUTES.EMPLOYEES), page: "Employees" },
  { path: toChildPath(ROUTES.ADD_STAFF), page: "AddStaff" },
  { path: "employees/:id", page: "EmployeeDetail" },
  { path: "employees/:id/edit", page: "EmployeeEdit" },
  { path: toChildPath(ROUTES.ATTENDANCE), page: "Attendance" },
  { path: toChildPath(ROUTES.FACE_ENROLLMENT), page: "FaceEnrollment" },
  { path: toChildPath(ROUTES.ATTENDANCE_MONITOR), page: "AttendanceMonitor" },
  { path: toChildPath(ROUTES.ATTENDANCE_DASHBOARD), page: "AttendanceDashboard" },
  { path: toChildPath(ROUTES.ATTENDANCE_REPORTS), page: "AttendanceReports" },
  { path: toChildPath(ROUTES.LEAVE_MANAGEMENT), page: "LeaveManagement" },
  { path: toChildPath(ROUTES.PAYROLL), page: "Payroll" },
  // Settings
  { path: toChildPath(ROUTES.GENERAL_SETTINGS), page: "GeneralSettings" },
  { path: toChildPath(ROUTES.USER_ROLE_MANAGEMENT), page: "UserRoleManagement" },
  { path: toChildPath(ROUTES.ADD_USER), page: "UserForm" },
  { path: "settings/users/:id", page: "UserDetail" },
  { path: "settings/users/:id/edit", page: "UserForm" },
  { path: toChildPath(ROUTES.INTEGRATIONS), page: "Integrations" },
  { path: toChildPath(ROUTES.NOTIFICATIONS), page: "Notifications" },
  { path: toChildPath(ROUTES.SECURITY_ACCESS), page: "SecurityAccess" },
  { path: toChildPath(ROUTES.LOGS), page: "ActivityLogs" },
  { path: "settings/logs/:id", page: "ActivityLogDetail" },
  // Additional modules
  { path: toChildPath(ROUTES.TABLE_OF_CONTENTS), page: "TableOfContents" },
  { path: toChildPath(ROUTES.PLAYBACK_SEARCH), page: "PlaybackSearch" },
  { path: toChildPath(ROUTES.THERMAL_IMAGING), page: "ThermalImaging" },
  { path: toChildPath(ROUTES.ALERTS_NOTIFICATIONS), page: "AlertsNotifications" },
  { path: toChildPath(ROUTES.INCIDENT_MANAGEMENT), page: "IncidentManagement" },
  { path: toChildPath(ROUTES.AI_INCIDENT_MANAGEMENT), page: "AIIncidentManagement" },
  { path: toChildPath(ROUTES.AI_MONITORING), page: "AIDetectionAlerts" },
  { path: toChildPath(ROUTES.AI_ALERTS_DASHBOARD), page: "ThermalAlerts" },
  { path: toChildPath(ROUTES.AI_ALERTS_HISTORY), page: "ZoneAlerts" },
  { path: toChildPath(ROUTES.AI_ALERTS_CONFIGURATION), page: "SystemAlerts" },
  { path: toChildPath(ROUTES.PEOPLE_DATABASE), page: "PeopleDatabase" },
  { path: toChildPath(ROUTES.PEOPLE_DATABASE_DETAIL), page: "PeopleDatabaseDetail" },
  { path: toChildPath(ROUTES.VEHICLE_DATABASE), page: "VehicleDatabase" },
  { path: toChildPath(ROUTES.VEHICLE_DATABASE_DETAIL), page: "VehicleDatabaseDetail" },
  { path: toChildPath(ROUTES.MOBILE_APP), page: "MobileApp" },
  { path: toChildPath(ROUTES.DATABASE_TABLES), page: "DatabaseTables" },
]